services:
  server:
    image: server
    build:
      context: .
      dockerfile: Server/Dockerfile

  businesslogic:
    image: businesslogic
    build:
      context: .
      dockerfile: BusinessLogic/Dockerfile

  server-1:
    image: server-1
    build:
      context: .
      dockerfile: Server/Dockerfile
